export const contacts = [
  {
    id: '1',
    name: 'Tony Stark',
    avatar: 'https://i.pravatar.cc/150?img=1',
    lastMessage: 'Hey Peter, update me on the project.',
    online: true,
    messages: [
      {
        id: 'm1',
        sender: 'Tony Stark',
        content: 'Hey Peter, update me on the project.',
        timestamp: '10:30 AM',
        isOwnMessage: false,
      },
      {
        id: 'm2',
        sender: 'You',
        content: 'Working on the frontend currently.',
        timestamp: '10:32 AM',
        isOwnMessage: true,
      },
    ],
  },
  {
    id: '2',
    name: 'Steve Rogers',
    avatar: 'https://i.pravatar.cc/150?img=2',
    lastMessage: 'Mission briefing at 6 PM.',
    online: false,
    messages: [
      {
        id: 'm3',
        sender: 'Steve Rogers',
        content: 'Mission briefing at 6 PM.',
        timestamp: '9:00 AM',
        isOwnMessage: false,
      },
    ],
  },
  {
    id: '3',
    name: 'Natasha Romanoff',
    avatar: 'https://i.pravatar.cc/150?img=5',
    lastMessage: `I'll handle the recon. Stay sharp.`,
    online: true,
    messages: [
      {
        id: 'm4',
        sender: 'Natasha Romanoff',
        content: 'Did you review the intel I sent?',
        timestamp: '8:15 AM',
        isOwnMessage: false,
      },
      {
        id: 'm5',
        sender: 'You',
        content: `Yeah, looks concerning. What's the plan?`,
        timestamp: '8:18 AM',
        isOwnMessage: true,
      },
      {
        id: 'm6',
        sender: 'Natasha Romanoff',
        content: `I'll handle the recon. Stay sharp.`,
        timestamp: '8:20 AM',
        isOwnMessage: false,
      },
    ],
  },
  {
    id: '4',
    name: 'Bruce Banner',
    avatar: 'https://i.pravatar.cc/150?img=8',
    lastMessage: 'The gamma readings are off the charts.',
    online: false,
    messages: [
      {
        id: 'm7',
        sender: 'You',
        content: 'Bruce, did the lab results come in?',
        timestamp: '7:45 AM',
        isOwnMessage: true,
      },
      {
        id: 'm8',
        sender: 'Bruce Banner',
        content: `Just got them. Something's not right.`,
        timestamp: '7:50 AM',
        isOwnMessage: false,
      },
      {
        id: 'm9',
        sender: 'You',
        content: 'How bad are we talking?',
        timestamp: '7:52 AM',
        isOwnMessage: true,
      },
      {
        id: 'm10',
        sender: 'Bruce Banner',
        content: 'The gamma readings are off the charts.',
        timestamp: '7:55 AM',
        isOwnMessage: false,
      },
    ],
  },
  {
    id: '5',
    name: 'Thor Odinson',
    avatar: 'https://i.pravatar.cc/150?img=11',
    lastMessage: 'Asgard needs our aid. Will you join me?',
    online: true,
    messages: [
      {
        id: 'm11',
        sender: 'Thor Odinson',
        content: 'Greetings, friend! How fare thee?',
        timestamp: '6:00 AM',
        isOwnMessage: false,
      },
      {
        id: 'm12',
        sender: 'You',
        content: `Doing well! What's up, Thor?`,
        timestamp: '6:05 AM',
        isOwnMessage: true,
      },
      {
        id: 'm13',
        sender: 'Thor Odinson',
        content: 'Asgard needs our aid. Will you join me?',
        timestamp: '6:07 AM',
        isOwnMessage: false,
      },
    ],
  },
  {
    id: '6',
    name: 'Wanda Maximoff',
    avatar: 'https://i.pravatar.cc/150?img=16',
    lastMessage: `I've been practicing the new techniques.`,
    online: false,
    messages: [
      {
        id: 'm14',
        sender: 'You',
        content: `How's the training going, Wanda?`,
        timestamp: 'Yesterday',
        isOwnMessage: true,
      },
      {
        id: 'm15',
        sender: 'Wanda Maximoff',
        content: 'Harder than I expected, but manageable.',
        timestamp: 'Yesterday',
        isOwnMessage: false,
      },
      {
        id: 'm16',
        sender: 'You',
        content: 'Let me know if you need a sparring partner.',
        timestamp: 'Yesterday',
        isOwnMessage: true,
      },
      {
        id: 'm17',
        sender: 'Wanda Maximoff',
        content: `I've been practicing the new techniques.`,
        timestamp: 'Yesterday',
        isOwnMessage: false,
      },
    ],
  },
  {
    id: '7',
    name: 'Sam Wilson',
    avatar: 'https://i.pravatar.cc/150?img=21',
    lastMessage: 'Redwing spotted something near the border.',
    online: true,
    messages: [
      {
        id: 'm18',
        sender: 'Sam Wilson',
        content: 'You free for a flight later?',
        timestamp: '11:00 AM',
        isOwnMessage: false,
      },
      {
        id: 'm19',
        sender: 'You',
        content: 'Depends — is it for fun or work?',
        timestamp: '11:03 AM',
        isOwnMessage: true,
      },
      {
        id: 'm20',
        sender: 'Sam Wilson',
        content: 'Redwing spotted something near the border.',
        timestamp: '11:05 AM',
        isOwnMessage: false,
      },
    ],
  },
  {
    id: '8',
    name: 'Clint Barton',
    avatar: 'https://i.pravatar.cc/150?img=33',
    lastMessage: 'Never miss. You know the motto.',
    online: false,
    messages: [
      {
        id: 'm21',
        sender: 'You',
        content: 'Clint, are you joining the op tomorrow?',
        timestamp: 'Monday',
        isOwnMessage: true,
      },
      {
        id: 'm22',
        sender: 'Clint Barton',
        content: `Wouldn't miss it.`,
        timestamp: 'Monday',
        isOwnMessage: false,
      },
      {
        id: 'm23',
        sender: 'You',
        content: 'Good. We need your precision.',
        timestamp: 'Monday',
        isOwnMessage: true,
      },
      {
        id: 'm24',
        sender: 'Clint Barton',
        content: 'Never miss. You know the motto.',
        timestamp: 'Monday',
        isOwnMessage: false,
      },
    ],
  },
  {
    id: '9',
    name: 'Nick Fury',
    avatar: 'https://i.pravatar.cc/150?img=50',
    lastMessage: 'This is above your clearance level. For now.',
    online: true,
    messages: [
      {
        id: 'm25',
        sender: 'Nick Fury',
        content: 'I need you in my office. Now.',
        timestamp: '9:30 AM',
        isOwnMessage: false,
      },
      {
        id: 'm26',
        sender: 'You',
        content: 'On my way. Everything okay?',
        timestamp: '9:31 AM',
        isOwnMessage: true,
      },
      {
        id: 'm27',
        sender: 'Nick Fury',
        content: 'This is above your clearance level. For now.',
        timestamp: '9:32 AM',
        isOwnMessage: false,
      },
    ],
  },
  {
    id: '10',
    name: 'Scott Lang',
    avatar: 'https://i.pravatar.cc/150?img=60',
    lastMessage: 'Cassie says hi, by the way 😄',
    online: true,
    messages: [
      {
        id: 'm28',
        sender: 'Scott Lang',
        content: 'Dude, the suit malfunctioned again.',
        timestamp: '2:00 PM',
        isOwnMessage: false,
      },
      {
        id: 'm29',
        sender: 'You',
        content: 'Again? What happened this time?',
        timestamp: '2:02 PM',
        isOwnMessage: true,
      },
      {
        id: 'm30',
        sender: 'Scott Lang',
        content: 'Got stuck at half-size for like an hour.',
        timestamp: '2:04 PM',
        isOwnMessage: false,
      },
      {
        id: 'm31',
        sender: 'You',
        content: 'Haha, are you okay though?',
        timestamp: '2:05 PM',
        isOwnMessage: true,
      },
      {
        id: 'm32',
        sender: 'Scott Lang',
        content: 'Cassie says hi, by the way 😄',
        timestamp: '2:06 PM',
        isOwnMessage: false,
      },
    ],
  },
];